language: php

php:
  - 5.3
  - 5.4

branches:
    only:
        - develop

env: 
  global: 
  - secure: |-
      f2qD0VH2Xr6jjJwg8q9LquwLd89zTyenicLbpV7MKaSH97plH1PD704po6x6\neomF9UBnJUu4pINWIz7xJIUjfq/48YavuJgM6GAAR/PNQB+q7EiNTE8zvG52\nw39JswbGXv6W41VyDD0c2620WSpiS1CViBNvw6hYIdKhlFDwpD0=
  - secure: |-
      J0uZU6mhN6QpkrFT3brW5JL0s63lQWu0MCEH+SALanh6WwJYyXZCgVzh8kgS\ndd4n//CZmN1OXBvgMaxtx7MoWm4xIszNpJ2YByY7t217KqvnqVV0oIbDMi/x\nijk4smzraXjBMfhUdlDaGkcrIj6smrtOXCTJezGArgN2N/+Rmxo=

before_script:

  # SauceLabs Connect
  - curl https://gist.github.com/everzet/5698159/raw/sauce_connect_setup.sh | bash

  # Apache + PHP
  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql
  - sudo a2enmod rewrite
  - sudo sed -i -e "s,/var/www,$(pwd),g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,AllowOverride None,AllowOverride All,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

  # MySQL
  - echo -e "[mysqld]\nlower_case_table_names = 1" > lowercase_tables.cnf
  - sudo mv lowercase_tables.cnf /etc/mysql/conf.d/
  - sudo /etc/init.d/mysql restart

  # Composer
  - curl http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

  # Application
  - mkdir -p protected/runtime
  - chmod -R 0777 protected/runtime assets
  - cp protected/config/local/common.sample.php protected/config/local/common.php
  - cp index.example.php index.php
  - cp .htaccess.sample .htaccess
  - mysql -e 'create database openeyes;'
  - php protected/yiic.php migrate --interactive=0
 
script: vendor/bin/behat -p ci
