language: php

php:
  - 5.3
  - 5.4

branches:
    only:
        - develop

notifications:
  email:
    - tests@openeyes.org.uk

env: 
  global:
  # SauceLabs credentials
  - secure: "MCX85EGrZYLSawAT3WtgafCRXy4Ua40hwEX++ZeKJUQmqJcEvPWrLOCUL08f\nXed6a4kMmFvBeXOOLsbphnkXV5N1BW1jIg1ZjIwcFWG42g+3g5XdZjnXCv8i\ntFzF345KayVCaLChLwsr4FSOsEdRONG1657bY/JS9Fyso/VmU0Y="
  - secure: "jEOUcoYgGUQ+6qNlO7cY7a60G2J7VFOHt3mbelaSUBs+JL3kjXPxxlbGZNFB\njDE1wc84MIaDu6KEnadK5WJT5esiEvOHbPn7sDdruxpYzSrxtxxGV1RFeHSE\nr/VjPguQlKnpWbj8ykPk83Ojxg5W8tCAc9Gg0uQv656ZMtzi8KM="

before_script:

  # SauceLabs Connect
  - curl https://gist.github.com/everzet/5698159/raw/sauce_connect_setup.sh | bash

  # Apache + PHP
  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql
  - sudo a2enmod rewrite
  - sudo sed -i -e "s,/var/www,$(pwd),g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,AllowOverride None,AllowOverride All,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

  # MySQL
  - echo -e "[mysqld]\nlower_case_table_names = 1" > lowercase_tables.cnf
  - sudo mv lowercase_tables.cnf /etc/mysql/conf.d/
  - sudo /etc/init.d/mysql restart

  # Composer
  - curl http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

  # Application
  - mkdir -p protected/runtime
  - chmod -R 0777 protected/runtime assets
  - cp protected/config/local/common.sample.php protected/config/local/common.php
  - cp index.example.php index.php
  - cp .htaccess.sample .htaccess
  - mysql -e 'create database openeyes;'
  - php protected/yiic.php migrate --interactive=0
 
script: vendor/bin/behat -p ci
