- apt: pkg={{item}}
  with_items:
    - libfreetype6
    - libfreetype6-dev
    - libfontconfig
  name: 'Wkhtmltox | Fonts | install packages'
- name: 'Accept License'
  shell: 'echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections'
  name: 'Wkhtmltox | Fonts | Accept MScorefonts EULA'
- apt: pkg=ttf-mscorefonts-installer
  name: 'Wkhtmltox | Fonts | Install MS Corefonts'
