---
- get_url:
    url: '{{wkhtmltox_download_url}}'
    dest: /root/wkhtmltox-{{wkhtmltox_minor_version}}.deb
  name: 'Wkhtmltox | download {{wkhtmltox_download_url}}'
- apt:
    deb: /root/wkhtmltox-{{wkhtmltox_minor_version}}.deb
  name: 'Wkhtmltox | Install deb'
- apt: pkg=xvfb
  name: 'Install Xvfb'
- include: 'font.yml'
  when: '{{wkhtmltox_install_fonts}}'

