---
# application tasks to be customized and to run after the main provision

# Install project dependencies
- name: Install composer dependencies (This can take up to 30 minutes to run)
  composer:
    command: "install"
    arguments: "--no-interaction"
    prefer_source: "yes"
    working_dir: "/var/www/openeyes"
    no_dev: "no"
  become: true
  become_user: vagrant


# Populate MySQL database TODO; Use info in all.yml / vars.yml
- name: Populate DB from dump file (when set)
  mysql_db:
    state: import
    name: openeyes
    target: "{{ openeyes.mysql_dump }}"
    login_user: "root"
    login_password: "{{ openeyes.mysql_root_password }}"
  when: openeyes.mysql_dump

- name: Create directories for Yii
  become: yes
  become_method: sudo
  file:
    path: "{{ item }}"
    mode: "0755"
    owner: "vagrant"
    group: "vagrant"
    state: directory
  with_items:
    - /var/www/openeyes/protected/runtime
    - /var/www/openeyes/assets

- name: Copy common.php into place
  command: creates=/var/www/openeyes/protected/config/local/common.php cp /var/www/openeyes/protected/config/local.sample/common.php /var/www/openeyes/protected/config/local/common.php

- name: Copy console.php into place
  command: creates=/var/www/openeyes/protected/config/local/console.php cp /var/www/openeyes/protected/config/local.sample/console.vagrant.php /var/www/openeyes/protected/config/local/console.php
