---
# Application tasks to be customized and to run after the main provision

# Kept seperate so as not to impact composer
- name: php5 - install xdebug
  apt: pkg="{{ php_xdebug }}" state=latest update_cache=yes
  when: php_xdebug is defined

- name: Copy xdebug INI into mods-available folder.
  template: >
    src=xdebug.ini.j2
    dest=/etc/php5/mods-available/xdebug.ini
    owner=root group=root mode=644
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty' and php_xdebug is defined

- name: Copy xdebug INI into conf.d folder.
  template: >
    src=xdebug.ini.j2
    dest=/etc/php5/conf.d/xdebug.ini
    owner=root group=root mode=644
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise' and php_xdebug is defined

# "Resolve" issues with the PHP.ini from geerlinguy.php being php7 specific. (Temp fix)
- name: (re)Move existing PHP.ini out of the way
  file:
    path: /etc/php5/apache2/php.ini
    state: absent

- name: Link configured PHP.ini into Apache
  file:
    src: /etc/php/7.0/apache2/php.ini
    dest: /etc/php5/apache2/php.ini
    state: link

# Remove XDebug SymLink from PHP CLI
- name: Disable XDebug in PHP CLI
  file:
    path: /etc/php5/cli/conf.d/20-xdebug.ini
    state: absent
  when: php_xdebug is defined

# Broken -> https://github.com/ansible/ansible-modules-extras/pull/1663
# Install package.json (http://docs.ansible.com/ansible/npm_module.html)
# - name: Install packages based on package.json.
#   npm: path=/var/www/openeyes
# Install JavaScript packages (http://docs.ansible.com/ansible/bower_module.html)
# - name: Install packages based on bower.json.
#   bower: path=/var/www/openeyes

# - name: Git clone OE Vendor dependencies
#   git:
#     repo: https://github.com/{{ item }}.git
#     dest: /var/www/openeyes/vendor
#     update: yes
#     force: yes
#   with_items:
#     - "{{ openeyes.vendor_repo }}"


# Install project dependencies using composer (http://docs.ansible.com/ansible/composer_module.html)
- name: Install / Update composer dependencies
  environment:
    COMPOSER_DISCARD_CHANGES: 1
  composer:
    command: "install"
    arguments: "--no-interaction"
    prefer_source: "yes"
    working_dir: "/var/www/openeyes"
    no_dev: "no"
  become: true
  become_user: vagrant

# Git Clone OE depenandcies
- name: Git clone OE dependencies
  git:
    repo: https://github.com/openeyes/{{ item }}.git
    dest: /var/www/openeyes/protected/modules/{{ item }}
    update: yes
    force: yes
  with_items:
    - "{{ openeyes.modules }}"

# Populate MySQL databases
- name: Populate databases from dump file (when set)
  mysql_db:
    state: import
    name: "{{ item }}"
    target: "{{ openeyes.mysql_dump }}"
    login_user: "root"
    login_password: "{{ openeyes.mysql_root_password }}"
  when: openeyes.mysql_dump
  with_items:
    - openeyes
    - openeyestest

# Add in banner (TODO: Only works if the sameple dataset loaded)
# - name: Add banner info into MySQL
#   command: mysql
#       --user={{ openeyes.mysql_user }}
#       --password={{ openeyes.mysql_password }} openeyes
#       --host=localhost
#       --execute="UPDATE openeyes.setting_installation s SET s.value='New openeyes installation' WHERE s.key='watermark'"

# Create required directories and assign users / groups / permissions
- name: Create directories for Yii
  become: true
  file:
    path: "{{ item }}"
    mode: "0775"
    owner: "vagrant"
    group: "www-data"
    state: directory
  with_items:
    - /var/www/openeyes/assets
    - /var/www/openeyes/cache
    - /var/www/openeyes/protected/cache
    - /var/www/openeyes/protected/cache/events
    - /var/www/openeyes/protected/runtime

# TODO Change to use a template
- name: Copy common.php into place
  command: creates=/var/www/openeyes/protected/config/local/common.php cp /var/www/openeyes/protected/config/local.sample/common.php /var/www/openeyes/protected/config/local/common.php

- name: Copy console.php into place
  command: creates=/var/www/openeyes/protected/config/local/console.php cp /var/www/openeyes/protected/config/local.sample/console.vagrant.php /var/www/openeyes/protected/config/local/console.php

# - name: Migrate using YIIC of openeyes DB
#   command: php /var/www/openeyes/protected/yiic.php migrate --interactive=0

# - name: Migrate Modules using YIIC of openeyes DB
#   command: php /var/www/openeyes/protected/yiic.php migratemodules --interactive=0

# - name: Migrate using YIIC of testdb
#   command: php /var/www/openeyes/protected/yiic.php migrate  --connectionID=testdb --interactive=0

# - name: Migrate Modules using YIIC of testdb
#   command: php /var/www/openeyes/protected/yiic.php migratemodules  --connectionID=testdb --interactive=0
