---
# application tasks to be customized and to run after the main provision

# Remove XDebug from PHP CLI
- name: Disable XDebug in PHP CLI
  file:
    path: /etc/php5/cli/conf.d/20-xdebug.ini
    state: absent
  become: yes
  become_method: sudo

# Install project dependencies
- name: Install composer dependencies (This can take up to 30 minutes to run the first time.)
  environment:
    COMPOSER_DISCARD_CHANGES: 1
  composer:
    command: "install"
    arguments: "--no-interaction"
    prefer_source: "yes"
    working_dir: "/var/www/openeyes"
    no_dev: "no"
  become: true
  become_user: vagrant

# Git Clone OE depenandcies
- name: Git clone OE dependencies
  git:
    repo: https://github.com/openeyes/{{ item }}.git
    dest: /var/www/openeyes/protected/modules/{{ item }}
  with_items:
    - eyedraw
    - sample

# Populate MySQL databases
- name: Populate databases from dump file (when set)
  mysql_db:
    state: import
    name: "{{ item }}"
    target: "{{ openeyes.mysql_dump }}"
    login_user: "root"
    login_password: "{{ openeyes.mysql_root_password }}"
  when: openeyes.mysql_dump
  with_items:
    - openeyes
    - openeyestest

# Add in banner (TODO: Only works if the sameple dataset loaded)
# - name: Add banner info into MySQL
#   command: mysql
#       --user={{ openeyes.mysql_user }}
#       --password={{ openeyes.mysql_password }} openeyes
#       --host=localhost
#       --execute="UPDATE openeyes.setting_installation s SET s.value='New openeyes installation' WHERE s.key='watermark'"

# Create required directories and assign users / groups / permissions
- name: Create directories for Yii
  become: yes
  become_method: sudo
  file:
    path: "{{ item }}"
    mode: "0775"
    owner: "vagrant"
    group: "www-data"
    state: directory
  with_items:
    - /var/www/openeyes/assets
    - /var/www/openeyes/cache
    - /var/www/openeyes/protected/cache
    - /var/www/openeyes/protected/cache/events
    - /var/www/openeyes/protected/runtime

- name: Copy common.php into place
  command: creates=/var/www/openeyes/protected/config/local/common.php cp /var/www/openeyes/protected/config/local.sample/common.php /var/www/openeyes/protected/config/local/common.php

- name: Copy console.php into place
  command: creates=/var/www/openeyes/protected/config/local/console.php cp /var/www/openeyes/protected/config/local.sample/console.vagrant.php /var/www/openeyes/protected/config/local/console.php

# - name: Migrate using YIIC of openeyes DB
#   command: php /var/www/openeyes/protected/yiic.php migrate --interactive=0

# - name: Migrate Modules using YIIC of openeyes DB
#   command: php /var/www/openeyes/protected/yiic.php migratemodules --interactive=0

# - name: Migrate using YIIC of testdb
#   command: php /var/www/openeyes/protected/yiic.php migrate  --connectionID=testdb --interactive=0

# - name: Migrate Modules using YIIC of testdb
#   command: php /var/www/openeyes/protected/yiic.php migratemodules  --connectionID=testdb --interactive=0
