#!/bin/bash

## Process command parameters
quiet=0
showhelp=0
for i in "$@"
do
case $i in
	--quiet|-q) quiet=1
	;;
    --help) showhelp=1
    ;;
	*)  echo "Unknown command line: $i"
    ;;
esac
done

# Show help text
if [ $showhelp = 1 ]; then
    echo ""
    echo "DESCRIPTION:"
    echo "Migrates database to latest schema"
    echo ""
    echo "usage: $0 [--help] [--quiet | -q]"
    echo ""
    echo "COMMAND OPTIONS:"
	echo ""
	echo "  --help         : Show this help"
    echo "  --quiet | -q   : Do not show console output"
	echo ""
    exit 1
fi

dir=$PWD
cd /var/www/openeyes/protected
if [ $quiet = 0 ]; then
    sudo ./yiic migrate --interactive=0
    sudo ./yiic migratemodules --interactive=0
else
	sudo touch /etc/openeyes/migrate.log
	sudo chmod 775 /etc/openeyes/migrate.log
	sudo ./yiic migrate --interactive=0 > /etc/openeyes/migrate.log
    sudo ./yiic migratemodules --interactive=0 >> /etc/openeyes/migrate.log
    echo "Migrations applied - see /etc/openeyes/migrate.log for more details"
fi
cd "$dir"
