#!/bin/bash

dir=$PWD

cd /var/www/openeyes/protected/modules/sample/sql

echo Clearing current database

echo "
drop database if exists openeyes;
create database openeyes;
grant all privileges on openeyes.* to 'openeyes'@'%' identified by 'openeyes';
flush privileges;
" > /tmp/openeyes-mysql-create.sql

mysql -u root "-ppassword" < /tmp/openeyes-mysql-create.sql
rm /tmp/openeyes-mysql-create.sql


echo Re-importing database
mysql -uopeneyes "-popeneyes" -D openeyes < openeyes_sample_data.sql

echo Performing database migrations
cd /var/www/openeyes/protected
./yiic migrate --interactive=0
./yiic migratemodules --interactive=0

cd "$dir"
printf "\e[42m\e[97m  RESET COMPLETE  \e[0m \n"
