#!/bin/bash

git config core.fileMode false

source /etc/openeyes/modules.conf
dir=$PWD

#  If -f was not specified on the command line, then check each module
#  to see if any changes are unstaged.

# Check out the PHP modules

cd /var/www/openeyes/protected/modules
for module in ${modules[@]}; do
  if [ ! "$module" = "openeyes" ] && [ ! -d "$module" ]; then
    printf "\e[31mModule $module not found\e[0m\n"
  else
    if [ ! "$module" = "openeyes" ]; then cd $module; fi
	if [ -d ".git" ]; then
		printf "\e[32m$module: \e[0m"
		if [ "$1" = "-f" ]; then git reset --hard; fi
		git pull
	fi
    if [ ! "$module" = "openeyes" ]; then cd ..; fi
  fi
done

# Check out the Java modules

cd /var/www/openeyes/protected/javamodules
for module in ${javamodules[@]}; do
  if [ ! -d "$module" ]; then
    printf "\e[31mModule $module not found\e[0m\n"
  else 
    cd $module
    git pull
    cd ..
  fi
done


# Now reset/relink various config files etc
oe-fix


cd "$dir"
printf "\e[42m\e[97m  UPDATE COMPLETE  \e[0m \n"
oe-which
echo ""

