#!/bin/bash

# call new script if it exists, or fall back to old installer script (which is no longer maintained)
if [ -f /var/www/openeyes/protected/scripts/oe-which.sh ]; then
	bash /var/www/openeyes/protected/scripts/oe-which.sh "$@"
	exit 0
fi

function gitbranch {
  branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
  if [ !$? = 0 ]; then
    branch="";
  else
    if [ "$branch" = "HEAD" ]; then branch=$(git describe --all 2>/dev/null); fi
    if [ ! "$branch" = "" ]; then echo $branch;
    fi
  fi
}

source /etc/openeyes/modules.conf

dir=$PWD

#Check openeyes core
cd /var/www/openeyes
b="$(gitbranch)"
printf "\e[32m%-20s\e[39m-- openeyes\n" $b

# Check PHP modules
cd /var/www/openeyes/protected/modules
if [ -d "sample" ]; then modules=(${modules[@]} sample); fi # Add sample DB to checkout if it exists

for module in ${modules[@]}; do
	if [ ! -d "$module" ]; then
		if [ ! "$module" = "openeyes" ]; then printf "\e[31mModule $module not found\e[0m\n"; fi
	else
		cd $module

		# Check if this is a git repo
		if [ -d ".git" ]; then
		  b="$(gitbranch)"
		  printf "\e[32m%-20s\e[39m-- $module\n" $b
		fi
		cd ..
	fi
done

echo Java modules:
cd  /var/www/openeyes/protected/javamodules/
for module in ${javamodules[@]}; do
  if [ ! -d "$module" ]; then
    printf "\e[31mModule $module not found\e[0m\n"
  else
    cd $module
    b="$(gitbranch)"
    cd ..
    printf "\e[32m%-20s\e[39m-- $module\n" $b
  fi
done

printf "Done\n\n"
cd "$dir"
