---
- src: angstwad.docker_ubuntu
  version: v1.1.10
- src: geerlingguy.apache
  version: 1.7.3
- src: geerlingguy.mysql
  version: 2.3.2
- src: geerlingguy.composer
  version: 1.4.2
- src: geerlingguy.nodejs
  version: 3.3.0
- src: zealot128.wkhtmltox